version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.0

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Run basic check
          command: node -v
          
  deploy:
    machine: true

    steps:
      - checkout

      - add_ssh_keys

      - run:
          name: Deploy to EC2
          command: |
            ssh -i "simpleapp-key.pem" ubuntu@ec2-98-93-64-105.compute-1.amazonaws.com "cd ~/SimpleApplication && git pull origin main && npm install && pm2 restart all || pm2 start npm --name mathapp -- start"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
